import Navbar from "@/components/navbar";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ThemeProvider } from "@/providers/next-theme-provider";
import { Toaster } from "@/providers/toaster-provider";
import AuthContext from "@/providers/auth-provider";
import { getSession } from "@/lib/session";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "rePix",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getSession();
  return (
    <html lang="en">
      <body suppressHydrationWarning className={inter.className}>
        <AuthContext>
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
            <Navbar session={session} />
            {children}
            <Toaster />
          </ThemeProvider>
        </AuthContext>
      </body>
    </html>
  );
}
